      { icon: 'x', link: 'https://x.com/evanyou' },
  {
    avatar: 'https://github.com/sapphi-red.png',
    name: 'sapphi-red',
    title: 'Web Developer',
    org: 'VoidZero',
    orgLink: 'https://voidzero.dev/',
    desc: 'Creator of Vue.js and Vite.',
    links: [
      { icon: 'github', link: 'https://github.com/sapphi-red' },
      { icon: 'bluesky', link: 'https://bsky.app/profile/sapphi.red' },
      { icon: 'twitter', link: 'https://twitter.com/sapphi_red' },
      { icon: 'mastodon', link: 'https://elk.zone/m.webtoo.ls/@sapphi_red' },
    ],
    sponsor: 'https://github.com/sponsors/sapphi-red',
  },
    org: 'Vercel',
    orgLink: 'https://vercel.com/',
    desc: 'Core team member of Vite & Vue. Working on Nuxt.',
    org: 'VoidZero',
    orgLink: 'https://voidzero.dev/',
    org: 'VoidZero',
    orgLink: 'https://voidzero.dev/',
  {
    avatar: 'https://github.com/dominikg.png',
    name: 'Dominik G.',
    title: 'Resident CI Expert',
    desc: 'Team Member of Vite and Svelte',
    links: [
      { icon: 'github', link: 'https://github.com/dominikg' },
      { icon: 'mastodon', link: 'https://elk.zone/m.webtoo.ls/@dominikg' },
    ],
    sponsor: 'https://github.com/sponsors/dominikg',
  },
export const advisors = [
  {
    avatar: 'https://github.com/serhalp.png',
    name: 'Philippe Serhal',
    title: 'Staff Software Engineer',
    org: 'Netlify',
    orgLink: 'https://www.netlify.com/',
    desc: 'Juggling all the frameworks at Netlify',
    links: [
      { icon: 'github', link: 'https://github.com/serhalp' },
      { icon: 'bluesky', link: 'https://bsky.app/profile/philippeserhal.com' },
    ],
  },
  {
    avatar: 'https://github.com/jamesopstad.png',
    name: 'James Opstad',
    title: 'Senior Engineer',
    org: 'Cloudflare',
    orgLink: 'https://www.cloudflare.com/',
    desc: 'Building developer tools at Cloudflare',
    links: [{ icon: 'github', link: 'https://github.com/jamesopstad' }],
  },
  {
    avatar: 'https://github.com/danielroe.png',
    name: 'Daniel Roe',
    title: 'Open Source Maintainer',
    org: 'Vercel',
    orgLink: 'https://vercel.com/',
    desc: 'Leading the Nuxt team',
    links: [
      { icon: 'github', link: 'https://github.com/danielroe' },
      { icon: 'bluesky', link: 'https://bsky.app/profile/danielroe.dev' },
    ],
    sponsor: 'https://github.com/sponsors/danielroe',
  },
]
