      { icon: 'x', link: 'https://x.com/evanyou' },
  {
    avatar: 'https://github.com/sapphi-red.png',
    name: 'sapphi-red',
    title: 'Web Developer',
    org: 'VoidZero',
    orgLink: 'https://voidzero.dev/',
    desc: 'Vite core team member. Call me sapphi or midori ;)',
    links: [
      { icon: 'github', link: 'https://github.com/sapphi-red' },
      { icon: 'bluesky', link: 'https://bsky.app/profile/sapphi.red' },
      { icon: 'twitter', link: 'https://twitter.com/sapphi_red' },
      { icon: 'mastodon', link: 'https://elk.zone/m.webtoo.ls/@sapphi_red' },
    ],
    sponsor: 'https://github.com/sponsors/sapphi-red',
  },
    org: 'Vercel',
    orgLink: 'https://vercel.com/',
    desc: 'Core team member of Vite & Vue. Working on Nuxt.',
    org: 'VoidZero',
    orgLink: 'https://voidzero.dev/',
    org: 'VoidZero',
    orgLink: 'https://voidzero.dev/',
  {
    avatar: 'https://github.com/dominikg.png',
    name: 'Dominik G.',
    title: 'Resident CI Expert',
    desc: 'Team Member of Vite and Svelte',
    links: [
      { icon: 'github', link: 'https://github.com/dominikg' },
      { icon: 'mastodon', link: 'https://elk.zone/m.webtoo.ls/@dominikg' },
    ],
    sponsor: 'https://github.com/sponsors/dominikg',
  },